### ISSUE TITLE
Add Buildtime Configuration Options

### ISSUE THREAD

**Issue by donaldwasserman** [maxwondercorn/ember-cli-barcode#6]
@maxwondercorn I know you said that you were doing some other updates, so I wanted to drop an issue rather than just a PR. 

Would you be interested in adding a build-time configuration option allowing the app to determine which version of the barcodejs library they want to load (rather than default to all)?

**Comment by maxwondercorn** [comment]
Yes, the would be great. That was a potential future feature but I never
looked into it.  Anything that can reduce payload size is a win.

I've made the updates that I wanted to do and the master is up to date.
Updated dependencies,  cleansed up the readme and fixed the Travis scripts
after I removed bower.json.  I'll wait to publish until after we can merge
the PR.  No rush.

**Comment by maxwondercorn** [comment]
@donaldwasserman 

I found that you can't include more than one barcode type in the options array as it generates an ember error when the component renders

`Uncaught TypeError: r.options(...)[n.format] is not a function`

for any option after the first one.   I wasn't sure if you'd seen this issue.  I'm testing as an addon, not the dummy app.

I think it's an issue caused in jsbarcode, but I'd need to download the repo and create non-minified versions of the barcode files to debug it.

I actually don't think this is a problem, we can still have a slimmer build if someone only needs one barcode type.  That's probably 90% of the use cases anyway.  We'd just need to modify the readme to reflect that.  

If we only have one option, it probably make sense to use a string like `'all'` instead of an array to specify it.

thoughts?

btw, broccoli is not my strong suit, so looking at the merge code for an addon I understand has given me some insight - thanks.

**Comment by donaldwasserman** [comment]
That’s fine - I’ll work on, but I thought I tested it with 3 random options
and all the tests passed. I’ll look into it.

Like you said, I just need one option anyway.
