### ISSUE TITLE
Latest release fails with BroccoliMergeTrees error

### ISSUE THREAD

**Issue by maxwondercorn** [maxwondercorn/ember-cli-barcode#9]
Lastest release v2.2 fails on ember serve with the following error:

```
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]
```

If installed directly from Github, rather than NPM it woks without issues.

Temporary fix is to install using

```
ember install https://github.com/maxwondercorn/ember-cli-barcode.git
```

**Comment by simonihmig** [comment]
My best **guess** is that the `vendor` folder is empty when installed as an npm package, because `.gitkeep` is excluded in `.npmignore` (rightfully), so the vendor tree is undefined in `treeForVendor`. As there is nothing meaningful inside it anyways, it should be enough to return the `barcodeTree` [here](https://github.com/maxwondercorn/ember-cli-barcode/blob/master/index.js#L71), without any `mergeTrees` call, i.e. ignore `vendorTree` altogether, whether undefined or not...
